#
# GlassFish configuration.
#
# Please read the comments for each configuration settings before modifying.
#

# application environment. Default value development
environment: development


# HTTP configuration
http:

    # port
    port: 3000
    
    #address
    address: 0.0.0.0

    # context root. The default value is '/'
    contextroot: /

    # Grizzly is NIO based HTTP libraries used by GlassFish gem
    grizzly:
        #HTTP chunking enable/disable
        chunking-enabled: true

        # Time after which the request times out in seconds
        request-timeout: 30
        
        #Send buffer size
        send-buffer-size: 8192
        
        #maximum number of keep-alive connections
        max-keepalive-connextions: 256
        
        #Keep Alive timeout, max time a connection can be deemed as idle and kept
        #in the keep-alive state
        keepalive-timeout: 30
                        
        #http thread pool used by Grizzly
        thread-pool:
            #Idle threads are removed from pool, after this time (in seconds)
            idle-thread-timeout-seconds: 900

            #The maxim number of tasks, which could be queued on the thread pool.
            #-1 disables any maximum checks.
            max-queue-size: 4096

            #Maximum number of threads in the threadpool servicing
            #requests in this queue. This is the upper bound on the no. of
            #threads that exist in the threadpool.
            max-thread-pool-size: 5

            #Minimum number of threads in the threadpool servicing
            #requests in this queue. These are created up front when this
            #threadpool is instantiated
            min-thread-pool-size: 2                

#Logging configuration
log:

    # Log file location. Default log file is log/<environment>.log. For 
    # example, if you are running in development environment, then the log 
    # file would be log/development.log.
    #
    # The log-file value must be either an absolute path or relative to your 
    # application directory.
    
    log-file: log.log

    # Logging level. Log level 0 to 7. 0:OFF, 1:SEVERE, 2:WARNING,
    # 3:INFO (default), 4:FINE, 5:FINER, 6:FINEST, 7:ALL.
    log-level: 3

#
# Runtime configuration
# If you are using Rails ver < 2.1.x, you should configure the JRuby runtime 
# pool for increased scalability.
jruby-runtime-pool:

    # Initial number of jruby runtimes that Glassfish starts with. It defaults
    # to one. It also represents the lowest value that Glassfish will use for
    # the maximum and the highest value that Glassfish will accept for the
    # minimum. As of this time, setting this number too high may cause
    # undesirable behavior. Default value is .
    initial: 1

    # Minimum number of jruby runtimes that will be available in the pool.
    # It defaults to one. The pool will always be at least this large, but
    # may well be larger than this. Default value is 1.
    min: 1


    # Maximum number of jruby runtimes that may be available in the pool.
    # It defaults to two. The pool will not neccessarily be this large.
    # Values that are too high may result in OutOfMemory errors, either in
    # the heap or in the PermGen. Default value is 1.
    max: 1

daemon:
    # Run GlassFish as a daemon. GlassFish may not run as a daemon process
    # on all platforms. Default value is false.
    enable: true

    # File where the process id of GlassFish is saved when run as daemon.
    # The location must be either an absolute path or relative to your 
    # application directory.
    # default PID file is tmp/pids/glassfish-<PID>.pid
    
    #pid:

    # Like JRuby GlassFish gem runs on Java Virtual Machine. You can pass
    # JVM properties using 'jvm-options' property. The JVM options must be
    # SPACE seprated.
    # 'jvm-options. property can ONLY be used only in daemon 
    # mode. The numbers below are to give an ideas. The numbers in your case 
    # would vary based on the hardware capabilities of machine you are 
    # running. See what is a server class machine 
    # http://java.sun.com/javase/6/docs/technotes/guides/vm/server-class.html

    # GlassFish gem runs with these default options
    #
    #jvm-options: -server -Xmx512m -XX:MaxPermSize=192m -XX:NewRatio=2 -XX:+DisableExplicitGC -Dhk2.file.directory.changeIntervalTimer=6000

    # Values below are given for a Sun Fire x4100, 4x Dual Core Opteron, 8G 
    # mem machine. You may like to changes these values according to the 
    # hardware you plan to run your application on. For details see
    # JVM ergonomics document, 
    # http://java.sun.com/javase/6/docs/technotes/guides/vm/gc-ergonomics.html
    #
    #jvm-options: -server -Xmx2500m -Xms64m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:NewRatio=2 -XX:+DisableExplicitGC -Dhk2.file.directory.changeIntervalTimer=6000



    